name: Deploy Frontend to EC2 via Nginx

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: pharmatc-front
        run: npm ci

      - name: Install additional packages
        working-directory: pharmatc-front
        run: |
          npm install xlsx file-saver
          npm install --save-dev @types/file-saver

      - name: Create .env.production
        run: echo "NEXT_PUBLIC_API_BASE_URL=http://3.25.208.164:8080" > pharmatc-front/.env.production

      - name: Build frontend
        working-directory: pharmatc-front
        run: npm run build

      # ✅ 디렉토리 미리 생성하고 ec2-user로 권한 변경
      - name: Ensure /var/www/pharmatc exists and has correct permission
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/pharmatc
            sudo chown -R ec2-user:ec2-user /var/www/pharmatc

      - name: Clean remote target directory (optional)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf /var/www/pharmatc/*

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "pharmatc-front/out/*"
          target: "/var/www/pharmatc"
          overwrite: true

      - name: Fix file permissions for nginx (optional)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown -R nginx:nginx /var/www/pharmatc

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart nginx
