name: Deploy Frontend to EC2 via Nginx

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: pharmatc-front
        run: npm ci

      - name: Install optional packages
        working-directory: pharmatc-front
        run: |
          npm install xlsx file-saver
          npm install --save-dev @types/file-saver

      - name: Build frontend
        working-directory: pharmatc-front
        run: npm run build

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "pharmatc-front/build/"
          target: "/home/ec2-user/frontend"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
