name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행됨

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pharmatc-front  # frontend 디렉토리로 이동

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # npm ci → npm install 로 변경 (충돌 방지)

      - name: Build and Export
        run: npm run build:static  # export 포함되도록 수정

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: your-firebase-project-id
          entryPoint: pharmatc-front
